package interfazUsuario;

import java.awt.Dimension;
import java.awt.Point;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import objetosNegocio.Prestamo;
import objetosNegocio.PublicacionED;
import objetosNegocio.Usuario;
import objetosServicio.Fecha;

/**
 * Cuadro de diálogo donde se selecciona el usuario y el libro de un préstamo.
 * @author Diego Valenzuela Parra y José Karim Franco Valencia
 */
public class DlgPrestamo extends javax.swing.JDialog {

    /**
     * Constructor que establece las características del cuadro de diálogo y la
     * operación a realizar con él.
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     * @param title Título del cuadro de diálogo
     * @param modal true si permite acceder fuera de los límites del cuadro de
     * diálogo, false en caso contrario
     * @param prestamo Contiene la información del prestamo para agregar o
     * eliminar del catálogo de prestamos.
     * @param listaLibros Es la lista de libros del catálogo de libros
     * @param listaUsuarios Es la lista de usuarios del catálogo de usuarios
     * @param operacion Operación a realizar en el cuadro de diálogo: AGREGAR =
     * 0, ACTUALIZAR = 1, ELIMINAR = 2;
     * @param respuesta Boton presionado al salir de los cuadros de * diálogos:
     * ACEPTAR = "Aceptar", CANCELAR = "Cancelar".
     */
    public DlgPrestamo(java.awt.Frame parent, String title, boolean modal, Prestamo prestamo, DefaultComboBoxModel listaUsuarios, DefaultComboBoxModel listaLibros, int operacion, StringBuffer respuesta) {
        super(parent, title, modal);
        this.prestamo = prestamo;
        this.listaUsuarios = listaUsuarios;
        this.listaLibros = listaLibros;
        this.operacion = operacion;
        this.respuesta = respuesta;
        initComponents();

        // Si la operación es agregar
        if (operacion == ConstantesGUI.AGREGAR) {
            botonAceptar.setText("Prestar");
        } // Si la operación es eliminar
        else if (operacion == ConstantesGUI.ELIMINAR) {
            botonAceptar.setText("Devolver");
            campoTextoTiempo.hide();
            etiquetaTiempo.hide();
        }

        // Establece el valor por omisión para respuesta, por si se cierra el
        // cuadro de diálogo presionando el botón cerrar o el botón cancelar
        respuesta.append(ConstantesGUI.CANCELAR);
        
        // centra el cuadro de dialogo sobre la ventana de la aplicación
        centraCuadroDialogo(parent);
        
        // Muestra el cuadro de diálogo
        setVisible(true);
    }

    /**
     * Este método centra el cuadro de dialogo sobre la ventana de la
     * aplicación.
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     */
    private void centraCuadroDialogo(java.awt.Frame parent) {
        // Obtiene el tamaño y posición de la ventana de la aplicación
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();
        // Obtiene el tamaño del cuadro de diálogo
        Dimension dlgSize = getPreferredSize();

        // Centra el cuadro de diálogo sobre la ventana padre
        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x,
                (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cajaCombinadaUsuarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cajaCombinadaLibros = new javax.swing.JComboBox<>();
        etiquetaTiempo = new javax.swing.JLabel();
        campoTextoTiempo = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonRestaurar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuario:");

        cajaCombinadaUsuarios.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cajaCombinadaUsuarios.setModel(listaUsuarios);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Libro:");

        cajaCombinadaLibros.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cajaCombinadaLibros.setModel(listaLibros);

        etiquetaTiempo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaTiempo.setText("Tiempo (días):");

        campoTextoTiempo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoTextoTiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTextoTiempoKeyTyped(evt);
            }
        });

        botonAceptar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setPreferredSize(new java.awt.Dimension(90, 30));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonRestaurar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonRestaurar.setText("Restaurar");
        botonRestaurar.setPreferredSize(new java.awt.Dimension(90, 30));
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setPreferredSize(new java.awt.Dimension(90, 30));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(etiquetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoTextoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaCombinadaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaCombinadaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(botonRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cajaCombinadaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaCombinadaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTiempo)
                    .addComponent(campoTextoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método oyente del botón botonAceptar.
     * @param evt Evento al que escucha.
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String tiempo = campoTextoTiempo.getText();
        // Si la opcion es agregar.
        if (operacion == ConstantesGUI.AGREGAR) {
            // Validación para prevenir que el tiempo sea un espacio en blanco.
            if (!tiempo.equals("")) {
                prestamo.setUsuario((Usuario) cajaCombinadaUsuarios.getSelectedItem());
                PublicacionED pubEDtmp = (PublicacionED) cajaCombinadaLibros.getSelectedItem();
                prestamo.setPublicacion(pubEDtmp.getPublicacion());
                prestamo.setFechaPrestamo(new Fecha());
                prestamo.setTiempoPrestamo(Integer.parseInt(campoTextoTiempo.getText()));
            
                // Borra el contenido de respuesta
                respuesta.delete(0, respuesta.length());
                
                // Establece que se presionó el botón botonAceptar
                respuesta.append(ConstantesGUI.ACEPTAR);
                
                // Destruye el cuadro de díalogo
                dispose();
            } else {
                // Mostrar error de mensaje
                JOptionPane.showMessageDialog(this, "Introduzca una cantidad válida.", "¡Error!", JOptionPane.ERROR_MESSAGE);
                campoTextoTiempo.setText("");
            }
        } // Si la operación es eliminar.
        else if (operacion == ConstantesGUI.ELIMINAR) {
            prestamo.setUsuario((Usuario) cajaCombinadaUsuarios.getSelectedItem());
            PublicacionED pubED = (PublicacionED) cajaCombinadaLibros.getSelectedItem();
            prestamo.setPublicacion(pubED.getPublicacion());
            
            // Borra el contenido de respuesta
            respuesta.delete(0, respuesta.length());
            
            // Establece que se presionó el botón botonAceptar
            respuesta.append(ConstantesGUI.ACEPTAR);
            
            // Destruye el cuadro de díalogo
            dispose();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * Método oyente del botón botonRestaurar.
     * @param evt Evento al que escucha.
     */
    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
        // Si la operación es agregar.
        if (operacion == ConstantesGUI.AGREGAR) {
            cajaCombinadaUsuarios.setSelectedIndex(0);
            cajaCombinadaLibros.setSelectedIndex(0);
            campoTextoTiempo.setText("");
        } // Si la operación es eliminar.
        else if (operacion == ConstantesGUI.ELIMINAR) {
            cajaCombinadaUsuarios.setSelectedIndex(0);
            cajaCombinadaLibros.setSelectedIndex(0);
        }
    }//GEN-LAST:event_botonRestaurarActionPerformed

    /**
     * Método oyente del botón botonCancelar.
     * @param evt Evento al que escucha.
     */
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // Destruye el cuadro de díalogo
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
    * Evento para prevenir que el usuario ingrese letras en el tiempo.
    * @param evt Evento al que escucha.
    */
    private void campoTextoTiempoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoTiempoKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == evt.VK_BACK_SPACE) || (c == evt.VK_DELETE))) {
            evt.consume(); // ignorar el evento de tecla
        }
    }//GEN-LAST:event_campoTextoTiempoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JComboBox<String> cajaCombinadaLibros;
    private javax.swing.JComboBox<String> cajaCombinadaUsuarios;
    private javax.swing.JTextField campoTextoTiempo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel listaLibros;
    private DefaultComboBoxModel listaUsuarios;
    private int operacion;
    private Prestamo prestamo;
    private StringBuffer respuesta;
}
